name: Daily GitHub Commit

on:
  schedule:
    - cron: "0 12 * * *"  # Runs every day at 12:00 PM UTC
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Disable default GITHUB_TOKEN

      - name: Set up Git
        run: |
          git config --global user.name "Gautam-Kundalia"
          git config --global user.email "gautamkundalia01@gmail.com"

      - name: Make changes
        run: |
          echo "Run date: $(date)" >> activity.txt

      - name: Commit and Push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git add activity.txt
          git commit -m "Automated commit $(date)" || echo "No changes to commit"
          git remote set-url origin https://Gautam-Kundalia:${{ secrets.GH_TOKEN }}@github.com/Gautam-Kundalia/GitHub-Activity-Automation.git
          git push origin main
